openapi: 3.0.3
info:
  title: Prometheus HTTP
  description: |
    The current stable HTTP API is reachable under /api/v1 on a Prometheus server. Any non-breaking additions will be added under that endpoint.
  version: v1
servers:
  - url: /api/v1
tags:
  - name: Expression query
    description: |
      Query language expressions may be evaluated at a single instant or over a range of time.
  - name: Querying metadata
    description: |
      Query metadata about series and their labels.
  - name: Default
  - name: Status
    description: |
      Expose current Prometheus configuration.
  - name: TSDB Admin API
    description: "Expose database functionalities for the advanced user. Requires --web.enable-admin-api.\n"
paths:
  /admin/tsdb/clean_tombstones:
    post:
      tags:
        - TSDB Admin API
      summary: Removes deleted data
      description: |
        CleanTombstones removes the deleted data from disk and cleans up the existing tombstones. This can be used after deleting series to free up space.
      operationId: cleanTombstones
      responses:
        204:
          description: Successful
          content: {}
  /admin/tsdb/delete_series:
    post:
      tags:
        - TSDB Admin API
      summary: Deletes selected data
      description: |
        DeleteSeries deletes data for a selection of series in a time range. The actual data still exists on disk and is cleaned up in future compactions or can be explicitly cleaned up by hitting the [Clean Tombstones](https://prometheus.io/docs/prometheus/latest/querying/api/#clean-tombstones) endpoint.

        **NOTE:** This endpoint marks samples from series as deleted, but will not necessarily prevent associated series metadata from still being returned in metadata queries for the affected time range (even after cleaning tombstones). The exact extent of metadata deletion is an implementation detail that may change in the future.
      operationId: deleteSeries
      parameters:
        - name: match
          in: query
          description: |
            Repeated label matcher argument that selects the series to delete. At least one match[] argument must be provided.
          required: true
          schema:
            type: array
            items:
              type: string
              format: series_selector
            minItems: 1
          explode: true
        - name: start
          in: query
          description: Start timestamp. Optional and defaults to minimum possible time.
          schema:
            type: string
            format: rfc3339 | unix_timestamp
        - name: end
          in: query
          description: |
            End timestamp. Optional and defaults to maximum possible time.
            
            Not mentioning both start and end times would clear all the data for the matched series in the database.
          schema:
            type: string
            format: rfc3339 | unix_timestamp
      responses:
        204:
          description: Successful
          content: {}
  /admin/tsdb/snapshot:
    post:
      tags:
        - TSDB Admin API
      summary: Creates Snapshot of current data
      description: |
        Snapshot creates a snapshot of all current data into ```snapshots/<datetime>-<rand>``` under the TSDB's data directory and returns the directory as response. It will optionally skip snapshotting data that is only present in the head block, and which has not yet been compacted to disk.
      operationId: createSnapshot
      parameters:
        - name: skip_head
          in: query
          description: |
            Skip data present in the head block. Optional.
          schema:
            type: boolean
      responses:
        200:
          description: The snapshot now exists at ```<data-dir>/snapshots/20171210T211224Z-2be650b6d019eb54```
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapshotCreateResponse'
              example:
                status: success
                data:
                  name: 20171210T211224Z-2be650b6d019eb54
  /alertmanagers:
    get:
      tags:
        - Default
      summary: Returns current alertmanager discovery
      description: |
        Returns an overview of the current state of the Prometheus alertmanager discovery

        Both the active and dropped Alertmanagers are part of the response.
      operationId: readAlertManagers
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertManagerReadResponse'
              example:
                status: success
                data:
                  activeAlertmanagers:
                    - url: http://127.0.0.1:9090/api/v1/alerts
                  droppedAlertmanagers:
                    - url: http://127.0.0.1:9093/api/v1/alerts
  /alerts:
    get:
      tags:
        - Default
      summary: Returns active alerts
      description: |
        The /alerts endpoint returns a list of all active alerts.

        As the /alerts endpoint is fairly new, it does not have the same stability guarantees as the overarching API v1.
      operationId: readAlerts
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertReadResponse'
              example:
                data:
                  alerts:
                    - activeAt: 2018-07-04T20:27:12.60602144+02:00
                      annotations: {}
                      labels:
                        alertname: my-alert
                      state: firing
                      value: 1e+00
                status: success
  /label/{label_name}/values:
    get:
      tags:
        - Querying metadata
      summary: Returns label values
      description: |
        The following endpoint returns a list of label values for a provided label name
        The `data` section of the JSON response is a list of string label values.

        **NOTE:** These API endpoints may return metadata for series for which there is no sample within the selected time range, and/or for series whose samples have been marked as deleted via the deletion API endpoint. The exact extent of additionally returned series metadata is an implementation detail that may change in the future.
      operationId: readLabelValues
      parameters:
        - name: label_name
          in: path
          description: Label name.
          required: true
          schema:
            type: string
        - name: start
          in: query
          description: Start timestamp.
          required: true
          schema:
            type: string
            format: rfc3339 | unix_timestamp
        - name: end
          in: query
          description: End timestamp.
          required: false
          schema:
            type: string
            format: rfc3339 | unix_timestamp
        - name: match
          in: query
          description: |
            Repeated series selector argument that selects the series from which to read the label values.
          required: false
          schema:
            type: array
            items:
              type: string
              format: series_selector
          explode: true
      responses:
        200:
          description: |
            Success

            This example queries for all label values for the job label
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelValuesReadResponse'
              example:
                status: success
                data:
                  - node
                  - prometheus
  /labels:
    get:
      tags:
        - Querying metadata
      summary: Returns label names
      description: |
        The following endpoint returns a list of label names.
        
        The `data` section of the JSON response is a list of string label names.
        **NOTE:** These API endpoints may return metadata for series for which there is no sample within the selected time range, and/or for series whose samples have been marked as deleted via the deletion API endpoint. The exact extent of additionally returned series metadata is an implementation detail that may change in the future.
      operationId: readLabelNames
      parameters:
        - name: start
          in: query
          description: |
            Start timestamp.
          required: false
          schema:
            type: string
            format: rfc3339 | unix_timestamp
        - name: end
          in: query
          description: |
            End timestamp.
          required: false
          schema:
            type: string
            format: rfc3339 | unix_timestamp
        - name: match
          in: query
          description: |
            Repeated series selector argument that selects the series from which to read the label values. Optional.
          schema:
            type: array
            items:
              type: string
              format: series_selector
          explode: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelNamesReadResponse'
              example:
                status: success
                data:
                  - __name__
                  - call
                  - code
                  - config
                  - dialer_name
                  - endpoint
                  - event
                  - goversion
                  - handler
                  - instance
                  - interval
                  - job
                  - le
                  - listener_name
                  - name
                  - quantile
                  - reason
                  - role
                  - scrape_job
                  - slice
                  - version
  /metadata:
    get:
      summary: Returns metric metadata
      description: |
        It returns metadata about metrics currently scrapped from targets. However, it does not provide any target information. This is considered experimental and might change in the future.

        The data section of the query result consists of an object where each key is a metric name and each value is a list of unique metadata objects, as exposed for that metric name across all targets.
      operationId: MetricMetadataReadResponse
      parameters:
        - name: limit
          in: query
          description: Maximum number of metrics to return.
          required: true
          schema:
            type: integer
            format: int32
        - name: metric
          in: query
          description: A metric name to filter metadata for. All metric metadata is retrieved if left empty.
          schema:
            type: string
      responses:
        200:
          description: |
            Success

            The following example returns two metrics. Note that the metric ```http_requests_total``` has more than one object in the list. At least one target has a value for ```HELP``` that do not match with the rest.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataReadResponse'
              example:
                status: success
                data:
                  cortex_ring_tokens:
                    - type: gauge
                      help: Number of tokens in the ring
                      unit: ""
                  http_requests_total:
                    - type: counter
                      help: Number of HTTP requests
                      unit: ""
                    - type: counter
                      help: Amount of HTTP requests
                      unit: ""
        201:
          description: |
            Success

            The following example returns metadata only for the metric ```http_requests_total```.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataReadResponse'
              example:
                status: success
                data:
                  http_requests_total:
                    - type: counter
                      help: Number of HTTP requests
                      unit: ""
                    - type: counter
                      help: Amount of HTTP requests
                      unit: ""
  /query:
    get:
      tags:
        - Expression query
      summary: Evaluates instant query
      description: |
        The following endpoint evaluates an instant query at a single point in time

        You can URL-encode these parameters directly in the request body by using the ```POST``` method and ```Content-Type: application/x-www-form-urlencoded``` header. This is useful when specifying a large query that may breach server-side URL character limits.

        The data section of the query result has the following format
        ```
        {
          "resultType": "matrix" | "vector" | "scalar" | "string",
          "result": <value>
        }
        ```
        ```<value>``` refers to the query result data, which has varying formats depending on the ```resultType```. See the [expression query result formats](https://prometheus.io/docs/prometheus/latest/querying/api/#expression-query-result-formats).
      operationId: evaluateQueryInstant
      parameters:
        - name: query
          in: query
          description: |
            Prometheus expression query string.
          required: true
          schema:
            type: string
        - name: time
          in: query
          description: |
            Evaluation timestamp. Optional.
            The current server time is used if the time parameter is omitted.
          schema:
            type: string
            format: rfc3339 | unix_timestamp
        - name: timeout
          in: query
          description: |
            Evaluation timeout. Optional. Defaults to and is capped by the value of the ```-query.timeout``` flag.
          schema:
            type: string
            format: duration
      responses:
        200:
          description: |
            Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryDataReadResponse'
              example:
                status: success
                data:
                  resultType: vector
                  result:
                    - metric:
                        __name__: up
                        job: prometheus
                        instance: localhost:9090
                      value:
                        - 1.435781451781E9
                        - "1"
                    - metric:
                        __name__: up
                        job: node
                        instance: localhost:9100
                      value:
                        - 1.435781451781E9
                        - "0"
  /query_exemplars:
    get:
      tags:
        - Expression query
      summary: Returns list of Exemplars
      description: |
        This is <b>experimental</b> and might change in the future. The following endpoint returns a list of exemplars for a valid PromQL query for a specific time range
      operationId: readQueryExemplars
      x-stability: experimental
      parameters:
        - name: query
          in: query
          description: |
            Prometheus expression query string.
          required: true
          schema:
            type: string
        - name: start
          in: query
          description: |
            Start timestamp.
          schema:
            type: string
            format: rfc3339 | unix_timestamp
        - name: end
          in: query
          description: |
            End timestamp.
          schema:
            type: string
            format: rfc3339 | unix_timestamp
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueryExemplarsReadResponse"
              example:
                status: success
                data:
                  - seriesLabels:
                      __name__: test_exemplar_metric_total
                      instance: localhost:8090
                      job: prometheus
                      service: bar
                    exemplars:
                      - labels:
                          traceID: EpTxMJ40fUus7aGY
                        value: "6"
                        timestamp: 1.600096945479E9
                  - seriesLabels:
                      __name__: test_exemplar_metric_total
                      instance: localhost:8090
                      job: prometheus
                      service: foo
                    exemplars:
                      - labels:
                          traceID: Olp9XHlq763ccsfa
                        value: "19"
                        timestamp: 1.600096955479E9
                      - labels:
                          traceID: hCtjygkIHwAN9vs4
                        value: "20"
                        timestamp: 1.600096965489E9
  /query_range:
    get:
      tags:
        - Expression query
      summary: Evaluates query over range of time.
      description: |
        The following endpoint evaluates an expression query over a range of time

        You can URL-encode these parameters directly in the request body by using the ```POST``` method and ```Content-Type: application/x-www-form-urlencoded``` header. This is useful when specifying a large query that may breach server-side URL character limits.

        The data section of the query result has the following format
        ```
        {
          "resultType": "matrix",
          "result": <value>
        }
        ```
        For the format of the ```<value>``` placeholder, see the [range-vector result format](https://prometheus.io/docs/prometheus/latest/querying/api/#range-vectors).
      operationId: evaluateQueryRange
      parameters:
        - name: query
          in: query
          description: |
            Prometheus expression query string.
          required: true
          schema:
            type: string
        - name: start
          in: query
          description: |
            Start timestamp.
          schema:
            type: string
            format: rfc3339 | unix_timestamp
        - name: end
          in: query
          description: |
            End timestamp.
          schema:
            type: string
            format: rfc3339 | unix_timestamp
        - name: step
          in: query
          description: |
            Query resolution step width in ```duration``` format or float number of seconds.
          schema:
            type: string
            format: duration | float
        - name: timeout
          in: query
          description: |
            Evaluation timeout. Optional. Defaults to and is capped by the value of the ```-query.timeout``` flag.
          schema:
            type: string
            format: duration
      responses:
        200:
          description: |
            Success

            The following example evaluates the expression ```up``` over a 30-second range with a query resolution of 15 seconds.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseQuery_range"
              example:
                status: success
                data:
                  resultType: matrix
                  result:
                    - metric:
                        __name__: up
                        job: prometheus
                        instance: localhost:9090
                      values:
                        - - 1.435781430781E9
                          - "1"
                        - - 1.435781445781E9
                          - "1"
                        - - 1.435781460781E9
                          - "1"
                    - metric:
                        __name__: up
                        job: node
                        instance: localhost:9091
                      values:
                        - - 1.435781430781E9
                          - "0"
                        - - 1.435781445781E9
                          - "0"
                        - - 1.435781460781E9
                          - "1"
  /rules:
    get:
      tags:
        - Default
      summary: Returns currently loaded rules
      description: |-
        The ```/rules``` API endpoint returns a list of alerting and recording rules that are currently loaded. In addition it returns the currently active alerts fired by the Prometheus instance of each alerting rule.

        As the ```/rules``` endpoint is fairly new, it does not have the same stability guarantees as the overarching API v1.
      operationId: readRules
      parameters:
        - name: type
          in: query
          description: |
            Return only the alerting rules (e.g. ```type=alert```) or the recording rules (e.g. ```type=record```). When the parameter is absent or empty, no filtering is done.
          schema:
            type: string
            enum:
              - alert
              - record
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RuleReadResponse'
              example:
                data:
                  groups:
                    - rules:
                        - alerts:
                            - activeAt: 2018-07-04T20:27:12.60602144+02:00
                              annotations:
                                summary: High request latency
                              labels:
                                alertname: HighRequestLatency
                                severity: page
                              state: firing
                              value: 1e+00
                          annotations:
                            summary: High request latency
                          duration: 600
                          health: ok
                          labels:
                            severity: page
                          name: HighRequestLatency
                          query: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
                          type: alerting
                        - health: ok
                          name: job:http_inprogress_requests:sum
                          query: sum by (job) (http_inprogress_requests)
                          type: recording
                      file: /rules.yaml
                      interval: 60
                      name: example
                status: success
  /series:
    get:
      tags:
        - Querying metadata
      summary: Returns time series
      description: |
        The following endpoint returns the list of time series that match a certain label set.

        You can URL-encode these parameters directly in the request body by using the ```POST``` method and ```Content-Type: application/x-www-form-urlencoded``` header. This is useful when specifying a large or dynamic number of series selectors that may breach server-side URL character limits.

        The ```data``` section of the query result consists of a list of objects that contain the label name/value pairs which identify each series.
      operationId: readSeries
      parameters:
        - name: start
          in: query
          description: |
            Start timestamp. Optional.
          schema:
            type: string
            format: rfc3339 | unix_timestamp
        - name: end
          in: query
          description: |
            End timestamp. Optional.
          schema:
            type: string
            format: rfc3339 | unix_timestamp
        - name: match
          in: query
          description: |
            Repeated series selector argument that selects the series to return. At least one ```match[]``` argument must be provided.
          required: true
          schema:
            type: array
            items:
              type: string
              format: series_selector
            minItems: 1
          explode: true
      responses:
        200:
          description: |
            Success

            The following example returns all series that match either of the selectors ```up``` or ```process_start_time_seconds{job="prometheus"}```
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSeries'
              example:
                status: success
                data:
                  - __name__: up
                    job: prometheus
                    instance: localhost:9090
                  - __name__: up
                    job: node
                    instance: localhost:9091
                  - __name__: process_start_time_seconds
                    job: prometheus
                    instance: localhost:9090
  /status/buildinfo:
    get:
      tags:
        - Status
      summary: Returns build information
      description: |
        The following endpoint returns various build information properties about the Prometheus server.
      operationId: readServerBuildInfo
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrometheusBuildInfoReadResponse'
              example:
                status: success
                data:
                  version: 2.13.1
                  revision: cb7cbad5f9a2823a622aaa668833ca04f50a0ea7
                  branch: master
                  buildUser: julius@desktop
                  buildDate: 20191102-16:19:59
                  goVersion: go1.13.1
  /status/config:
    get:
      tags:
        - Status
      summary: Returns configuration file
      description: |
        The following endpoint returns currently loaded configuration file

        The config is returned as dumped YAML file.
        Due to limitation of the YAML library, YAML comments are not included.
      operationId: readServerConfig
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrometheusConfigReadResponse'
              example:
                status: success
                data:
                  yaml: <content of the loaded config file in YAML>
  /status/flags:
    get:
      tags:
        - Status
      summary: Returns flag values
      description: |
        The following endpoint returns flag values that Prometheus was configured with.
      operationId: readServerFlags
      responses:
        200:
          description: ""
          content:
            application/json:
              example:
                status: success
                data:
                  alertmanager.notification-queue-capacity: "10000"
                  alertmanager.timeout: 10s
                  log.level: info
                  query.lookback-delta: 5m
                  query.max-concurrency: "20"
  /status/runtimeinfo:
    get:
      tags:
        - Status
      summary: Returns runtime info
      description: |
        The following endpoint returns various runtime information properties about the Prometheus server

        The returned values are of different types, depending on the nature
        of the runtime property

        ---
        **NOTE:** The exact returned runtime properties may change without notice between Prometheus versions.

        ---

        New in v2.14
      operationId: readServerRuntimeInfo
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RuntimeInfoResponse'
              example:
                status: success
                data:
                  startTime: 2019-11-02T17:23:59.301361365+01:00
                  CWD: /
                  reloadConfigSuccess: true
                  lastConfigTime: 2019-11-02T17:23:59+01:00
                  timeSeriesCount: 873
                  corruptionCount: 0
                  goroutineCount: 48
                  GOMAXPROCS: 4
                  GOGC: ""
                  GODEBUG: ""
                  storageRetention: 15d
  /status/tsdb:
    get:
      tags:
        - Status
      summary: Returns statistics about TSBD
      description: |
        The following endpoint returns various cardinality statistics about the Prometheus TSDB

        Response Data
        ---

        **headStats:** This provides the following data about the head block of the TSDB:
        >**numSeries:** The number of series.
        **chunkCount:** The number of chunks.
        **minTime:** The current minimum timestamp in milliseconds.
        **maxTime:** The current maximum timestamp in milliseconds.

        **seriesCountByMetricName:** This will provide a list of metrics names and their series count.
        **labelValueCountByLabelName:** This will provide a list of the label names and their value count.
        **memoryInBytesByLabelName:** This will provide a list of the label names and memory used in bytes. Memory usage is calculated by adding the length of all values for a given label name.
        **seriesCountByLabelPair:** This will provide a list of label value pairs and their series count.
      operationId: readServerTSDBStatus
      responses:
        200:
          description: |
            Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TsdbStatusReadResponse'
              example:
                status: success
                data:
                  headStats:
                    numSeries: 508
                    chunkCount: 937
                    minTime: 1591516800000
                    maxTime: 1598896800143
                  seriesCountByMetricName:
                    - name: net_conntrack_dialer_conn_failed_total
                      value: 20
                    - name: prometheus_http_request_duration_seconds_bucket
                      value: 20
                  labelValueCountByLabelName:
                    - name: __name__
                      value: 211
                    - name: event
                      value: 3
                  memoryInBytesByLabelName:
                    - name: __name__
                      value: 8266
                    - name: instance
                      value: 28
                  seriesCountByLabelValuePair:
                    - name: job=prometheus
                      value: 425
                    - name: instance=localhost:9090
                      value: 425
  /status/walreplay:
    get:
      tags:
        - Status
      summary: Returns info about WAL replay.
      description: "The following endpoint returns information about the WAL replay\n\
        \nResponse Data\n---\n\n**read:** The number of segments replayed so far.\
        \ \n**total:** The total number segments needed to be replayed. \n**progress:**\
        \ The progress of the replay (0 - 100%). \n**state:** The state of the replay.\
        \ \n**Possible states:** \n  - **waiting:** Waiting for the replay to start.\
        \ \n  - **in progress:** The replay is in progress. \n  - **done:** The replay\
        \ has finished.\n  \n---\n**NOTE:** This endpoint is available before the\
        \ server has been marked ready and is updated in real time to facilitate monitoring\
        \ the progress of the WAL replay.\n\n---\n\nNew in v2.28\n"
      operationId: readServerWALReplayStatus
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalReplayStatusReadResponse'
              example:
                status: success
                data:
                  min: 2
                  max: 5
                  current: 40
                  state: in progress
  /targets:
    get:
      tags:
        - Default
      summary: Returns current target discovery.
      description: |
        Both the active and dropped targets are part of the response by default. ```labels``` represents the label set after relabelling has occurred. ```discoveredLabels``` represent the unmodified labels retrieved during service discovery before relabelling has occurred.
      operationId: readTargets
      parameters:
        - name: state
          in: query
          description: |
            The ```state``` query parameter allows the caller to filter by active or dropped targets, (e.g., ```state=active```, ```state=dropped```, ```state=any```).
          schema:
            type: string
            enum:
              - active
              - dropped
              - any
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TargetDiscoveryReadResponse'
              example:
                status: success
                data:
                  activeTargets:
                    - discoveredLabels:
                        __address__: 127.0.0.1:9090
                        __metrics_path__: /metrics
                        __scheme__: http
                        job: prometheus
                      labels:
                        instance: 127.0.0.1:9090
                        job: prometheus
                      scrapePool: prometheus
                      scrapeUrl: http://127.0.0.1:9090/metrics
                      globalUrl: http://example-prometheus:9090/metrics
                      lastError: ""
                      lastScrape: 2017-01-17T15:07:44.723715405+01:00
                      lastScrapeDuration: 0.050688943
                      health: up
                  droppedTargets:
                    - discoveredLabels:
                        __address__: 127.0.0.1:9100
                        __metrics_path__: /metrics
                        __scheme__: http
                        job: node
        201:
          description: |
            Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TargetDiscoveryReadResponse'
              example:
                status: success
                data:
                  activeTargets:
                    - discoveredLabels:
                        __address__: 127.0.0.1:9090
                        __metrics_path__: /metrics
                        __scheme__: http
                        job: prometheus
                      labels:
                        instance: 127.0.0.1:9090
                        job: prometheus
                      scrapePool: prometheus
                      scrapeUrl: http://127.0.0.1:9090/metrics
                      globalUrl: http://example-prometheus:9090/metrics
                      lastError: ""
                      lastScrape: 2017-01-17T15:07:44.723715405+01:00
                      lastScrapeDuration: 50688943
                      health: up
                  droppedTargets: []
  /targets/metadata:
    get:
      tags:
        - Default
      summary: Returns target metadata
      description: |-
        The following endpoint returns metadata about metrics currently scraped from targets. This is experimental and might change in the future.

        The ```data``` section of the query result consists of a list of objects that contain metric metadata and the target label set.
      operationId: readTargetMetadata
      x-stability: experimental
      parameters:
        - name: match_target
          in: query
          description: |
            Label selectors that match targets by their label sets. All targets are selected if left empty.
          schema:
            type: string
            format: label_selectors
        - name: metric
          in: query
          description: |
            A metric name to retrieve metadata for. All metric metadata is retrieved if left empty.
          schema:
            type: string
        - name: limit
          in: query
          description: |
            Maximum number of targets to match.
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: |
            Success

            The following example returns all metadata entries for the ```go_goroutines``` metric from the first two targets with label ```job="prometheus"```.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseTargetMetadata'
              example:
                status: success
                data:
                  - target:
                      instance: 127.0.0.1:9090
                      job: prometheus
                    type: gauge
                    help: Number of goroutines that currently exist.
                    unit: ""
                  - target:
                      instance: 127.0.0.1:9091
                      job: prometheus
                    type: gauge
                    help: Number of goroutines that currently exist.
                    unit: ""
        201:
          description: |
            Success

            The following example returns metadata for all metrics for all targets with label ```instance="127.0.0.1:9090```.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseTargetMetadata'
              example:
                status: success
                data:
                  - target:
                      instance: 127.0.0.1:9090
                      job: prometheus
                    type: gauge
                    help: Number of goroutines that currently exist.
                    unit: ""
                  - target:
                      instance: 127.0.0.1:9091
                      job: prometheus
                    type: gauge
                    help: Number of goroutines that currently exist.
                    unit: ""
components:
  schemas:
    # Response Schemas
    AlertManagerReadResponse:
      type: object
      properties:
        status:
          type: string
        data:
          $ref: '#/components/schemas/AlertManagerDiscovery'
      description: AlertManager response.
    AlertReadResponse:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            alerts:
              type: array
              items:
                $ref: '#/components/schemas/Alert'
      description: AlertManager response.
    RuleReadResponse:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            groups:
              type: array
              items:
                $ref: '#/components/schemas/RuleGroup'
      description: RuleReadResponse has info for all rules
    RuntimeInfoResponse:
      type: object
      properties:
        status:
          type: string
        data:
          $ref: '#/components/schemas/RuntimeInfo'
      description: RuntimeInfo about the Prometheus instance
    SnapshotCreateResponse:
      type: object
      properties:
        status:
          type: string
        data:
          $ref: '#/components/schemas/Snapshot'
      description: Snapshot created response
    LabelValuesReadResponse:
      type: object
      properties:
        status:
          type: string
        data:
          $ref: '#/components/schemas/LabelValues'
      description: LabelValues read response
    LabelNamesReadResponse:
      type: object
      properties:
        status:
          type: string
        data:
          $ref: '#/components/schemas/LabelNames'
      description: LabelNames read response
    MetadataReadResponse:
      type: object
      properties:
        status:
          type: string
        data:
          $ref: '#/components/schemas/LabelNames'
      description: MetadataReadResponse read response
    PrometheusConfigReadResponse:
      type: object
      properties:
        status:
          type: string
        data:
          $ref: '#/components/schemas/PrometheusConfig'
      description: PrometheusConfig read response
    PrometheusBuildInfoReadResponse:
      type: object
      properties:
        status:
          type: string
        data:
          $ref: '#/components/schemas/PrometheusBuildInfo'
      description: PrometheusBuildInfo read response
    QueryDataReadResponse:
      type: object
      properties:
        status:
          type: string
        data:
          $ref: '#/components/schemas/QueryData'
      description: QueryData read response
    QueryExemplarsReadResponse:
      type: object
      properties:
        status:
          type: string
        data:
          $ref: '#/components/schemas/QueryExemplars'
      description: QueryExemplars read response
    WalReplayStatusReadResponse:
      type: object
      properties:
        status:
          type: string
        data:
          $ref: '#/components/schemas/WalReplayStatus'
      description: WalReplayStatus read response
    TargetDiscoveryReadResponse:
      type: object
      properties:
        status:
          type: string
        data:
          $ref: '#/components/schemas/TargetDiscovery'
      description: TargetDiscovery read response
    TsdbStatusReadResponse:
      type: object
      properties:
        status:
          type: string
        data:
          $ref: '#/components/schemas/TsdbStatus'
      description: TsdbStatus read response
    # Models
    Alert:
      type: object
      properties:
        labels:
          type: object
          additionalProperties:
            type: string
        annotations:
          type: object
          additionalProperties:
            type: string
        state:
          $ref: '#/components/schemas/AlertState'
        activeAt:
          type: string
          format: unix_timestamp
        value:
          type: string
      description: Alert has info for an alert.
    AlertManagerDiscovery:
      type: object
      properties:
        activeAlertmanagers:
          type: array
          items:
            $ref: '#/components/schemas/AlertmanagerTarget'
        droppedAlertmanagers:
          type: array
          items:
            $ref: '#/components/schemas/AlertmanagerTarget'
      description: AlertManagerDiscovery has all the active Alertmanagers.
    AlertmanagerTarget:
      type: object
      properties:
        url:
          type: string
      description: AlertmanagerTarget has info on one AM.
    DiscoveredLabels:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
      description: Labels before any processing.
    DroppedTarget:
      type: object
      properties:
        discoveredLabels:
          $ref: '#/components/schemas/DiscoveredLabels'
      description: DroppedTarget has the information for one target that was dropped
        during relabelling.
    HeadStats:
      type: object
      properties:
        chunkCount:
          type: integer
          format: int64
        maxTime:
          type: integer
          format: int64
        minTime:
          type: integer
          format: int64
        numLabelPairs:
          type: integer
          format: int64
        numSeries:
          type: integer
          format: uint64
      description: HeadStats has information about the TSDB head.
    Label:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
      description: Label is a key/value pair of strings.
    Labels:
      type: array
      description: |-
        Labels is a sorted set of labels. Order has to be guaranteed upon
        instantiation.
      items:
        $ref: '#/components/schemas/Label'
    MetricType:
      type: string
      description: MetricType represents metric type values.
    PrometheusBuildInfo:
      type: object
      properties:
        branch:
          type: string
        buildDate:
          type: string
        buildUser:
          type: string
        goVersion:
          type: string
        revision:
          type: string
        version:
          type: string
      description: PrometheusBuildInfo contains build information about Prometheus.
    RuleGroup:
      type: object
      properties:
        evaluationTime:
          type: number
          format: double
        file:
          type: string
        interval:
          type: integer
          format: int32
          description: Interval at which the rule group is evaluated.This is the number of seconds between evaluations.
        lastEvaluation:
          type: string
          format: "rfc3339 | unix_timestamp"
          description: Last time the rule group was evaluated.
        name:
          type: string
        rules:
          type: array
          description: |-
            In order to preserve rule ordering, while exposing type (alerting or recording)
            specific properties, both alerting and recording rules are exposed in the
            same array.
          items:
            $ref: '#/components/schemas/Rule'
      description: RuleGroup has info for rules which are part of a group
    RuntimeInfo:
      type: object
      properties:
        CWD:
          type: string
        GODEBUG:
          type: string
        GOGC:
          type: string
        GOMAXPROCS:
          type: integer
          format: int
        corruptionCount:
          type: integer
          format: int64
        goroutineCount:
          type: integer
          format: int
        lastConfigTime:
          type: string
          format: "rfc3339 | unix_timestamp"
        reloadConfigSuccess:
          type: boolean
        startTime:
          type: string
          format: "rfc3339 | unix_timestamp"
        storageRetention:
          type: string
      description: RuntimeInfo contains runtime information about Prometheus.
    Target:
      type: object
      properties:
        discoveredLabels:
          $ref: '#/components/schemas/DiscoveredLabels'
        labels:
          $ref: '#/components/schemas/Labels'
        scrapePool:
          type: string
        scrapeURL:
          type: string
        globalURL:
          type: string
        lastError:
          type: string
        lastScrape:
          type: string
          format: "rfc3339 | unix_timestamp"
        lastScrapeDuration:
          type: number
          format: double
        health:
          $ref: '#/components/schemas/TargetHealth'
      description: Target has the information for one target.
    TargetDiscovery:
      type: object
      properties:
        activeTargets:
          type: array
          items:
            $ref: '#/components/schemas/Target'
        droppedTargets:
          type: array
          items:
            $ref: '#/components/schemas/DroppedTarget'
      description: TargetDiscovery has all the active targets.
    TargetHealth:
      type: string
      description: TargetHealth describes the health state of a target.
    Metadata:
      type: object
      properties:
        help:
          type: string
        type:
          $ref: '#/components/schemas/MetricType'
        unit:
          type: string
    MetricMetadata:
      type: object
      properties:
        help:
          type: string
        metric:
          type: string
        target:
          $ref: '#/components/schemas/Labels'
        type:
          $ref: '#/components/schemas/MetricType'
        unit:
          type: string
    PrometheusConfig:
      type: object
      properties:
        yaml:
          type: string
      description: a dumped YAML file
    QueryData:
      type: object
      properties:
        result:
          type: object
          properties:
            metric:
              type: object
              properties:
                __name__:
                  type: string
                job:
                  type: string
                instance:
                  type: string
            value:
              type: array
              items:
                oneOf:
                  - type: string
                    format: "unix_timestamp"
                  - type: string
                    format: "sample_value"
        resultType:
          type: string
          enum:
            - matrix
            - vector
            - scalar
            - string
    responseSeries:
      type: array
      description: a list of objects that contain the label name/value pairs which
        identify each series
      items:
        type: object
        properties:
          __name__:
            type: string
          job:
            type: string
          instance:
            type: string
    Snapshot:
      type: object
      properties:
        name:
          type: string
    QueryExemplars:
      type: object
      properties:
        seriesLabels:
          type: object
          properties:
            __name__:
              type: string
            job:
              type: string
            instance:
              type: string
            service:
              type: string
        exemplars:
          type: object
          properties:
            labels:
              type: object
              properties:
                traceID:
                  type: string
            values:
              type: string
            timestamp:
              type: string
              format: "unix_timestamp"
    responseQuery_range:
      type: object
      properties:
        resultType:
          type: string
        result:
          type: object
          properties:
            metric:
              type: object
              properties:
                __name__:
                  type: string
                job:
                  type: string
                instance:
                  type: string
            values:
              type: array
              items:
                oneOf:
                  - type: string
                    format: "unix_timestamp"
                  - type: string
                    format: "sample_value"
    MetadataMap:
      type: object
      properties:
        metricName:
          type: string
      additionalProperties:
        $ref: '#/components/schemas/Metadata'
      description: a (key, object) map. `metric name`is an example key
    LabelValues:
      type: array
      description: a list of string label values
      items:
        type: string
    LabelNames:
      type: array
      description: a list of string label names
      items:
        type: string
    responseTargetMetadata:
      type: array
      description: A list of objects
      items:
        $ref: '#/components/schemas/MetricMetadata'
    Rule:
      type: object
      properties:
        name:
          type: string
          description: Rule name
        query:
          type: string
          description: PromQL expression
        labels:
          type: object
          additionalProperties:
            type: string
        annotations:
          type: object
          additionalProperties:
            type: string
        health:
          type: string
          enum:
            - ok
          description: Rule health
        state:
          $ref: '#/components/schemas/AlertState'
        type:
          type: string
          enum:
            - alerting
            - recording
          description: Rule type
        duration:
          type: integer
          format: int32
          description: duration in seconds
        alerts:
          type: array
          description: A list of active alerts
          items:
            $ref: '#/components/schemas/Alert'
        lastEvaluation:
          type: string
          format: "rfc3339 | unix_timestamp"
          description: Last time the rule was evaluated
        evaluationTime:
          type: number
          format: float64
          description: Time it took to evaluate the rule
      required:
        - name
        - query
        - health
        - type
    AlertState:
      type: string
      enum:
        - firing
        - pending
        - inactive
      description: The state of an alert.
    Stat:
      type: object
      properties:
        name:
          type: string
        value:
          type: integer
          format: uint64
      description: stat holds the information about individual cardinality.
    TsdbStatus:
      type: object
      properties:
        HeadStats:
          $ref: '#/components/schemas/HeadStats'
        LabelValueCountByLabelName:
          type: array
          description: This will provide a list of the label names and their value
            count.
          items:
            $ref: '#/components/schemas/Stat'
        MemoryInBytesByLabelName:
          type: array
          description: This will provide a list of the label names and memory used
            in bytes. Memory usage is calculated by adding the length of all values
            for a given label name.
          items:
            $ref: '#/components/schemas/Stat'
        SeriesCountByLabelValuePair:
          type: array
          description: This will provide a list of label value pairs and their series
            count.
          items:
            $ref: '#/components/schemas/Stat'
        SeriesCountByMetricName:
          type: array
          description: This will provide a list of metrics names and their series
            count.
          items:
            $ref: '#/components/schemas/Stat'
      description: tsdbStatus has information of cardinality statistics from postings.
    WalReplayStatus:
      type: object
      properties:
        current:
          type: integer
          format: int
        max:
          type: integer
          format: int
        min:
          type: integer
          format: int
  securitySchemes:
    Basic:
      type: http
      scheme: basic
